=== youngd24/tfd/interfaces/edi/XML/204.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    204.dtd

    204 Document Type Definition

    $Id: 204.dtd,v 1.6 2003/01/09 21:15:30 youngd Exp $

    Contents Copyright (c) 2002-2003, The Freight Depot

    Darren Young [darren_young@yahoo.com]
-->

<!ELEMENT xmledi (transmission, shipment)>
<!ATTLIST xmledi doctype (204) #REQUIRED >

    <!ELEMENT transmission (timestamp, mode, ack)>
    <!ATTLIST transmission id CDATA #REQUIRED >
        <!ELEMENT timestamp (#PCDATA)>
        <!ELEMENT mode (#PCDATA)>
        <!ELEMENT ack (#PCDATA)>
   
   <!ELEMENT shipment (header, location, product, pickup, services)>
        <!ELEMENT header (type, paymentmethod, bolnumber, ponumber)>
            <!ELEMENT type (#PCDATA)>
            <!ELEMENT paymentmethod (#PCDATA)>
            <!ELEMENT bolnumber (#PCDATA)>
            <!ELEMENT ponumber (#PCDATA)>
        <!ELEMENT location (party+)>
            <!ELEMENT party (name, address1?, address2?, city?, state?, zip?, contact?, phone?, scac?)>
            <!ATTLIST party type (BILLING | CARRIER | DESTINATION | ORIGIN) #REQUIRED >
                <!ELEMENT name (#PCDATA)>
                <!ELEMENT address1 (#PCDATA)>
                <!ELEMENT address2 (#PCDATA)>
                <!ELEMENT city (#PCDATA)>
                <!ELEMENT state (#PCDATA)>
                <!ELEMENT zip (#PCDATA)>
                <!ELEMENT contact (#PCDATA)>
                <!ELEMENT phone (#PCDATA)>
                <!ELEMENT scac (#PCDATA)>
        <!ELEMENT product (description, weight, class, units, packaging, hazmat, hazmatphone)>
            <!ELEMENT description (#PCDATA)>
            <!ELEMENT weight (#PCDATA)>
            <!ELEMENT class (#PCDATA)>
            <!ELEMENT units (#PCDATA)>
            <!ELEMENT packaging (#PCDATA)>
            <!ELEMENT hazmat (#PCDATA)>
            <!ELEMENT hazmatphone (#PCDATA)>
        <!ELEMENT pickup (pickupdate, pickupafter, pickupbefore)>
            <!ELEMENT pickupdate (#PCDATA)>
            <!ELEMENT pickupafter (#PCDATA)>
            <!ELEMENT pickupbefore (#PCDATA)>
        <!ELEMENT services (accessorial+)>
            <!ELEMENT accessorial (#PCDATA)>

=== youngd24/tfd/interfaces/edi/XML/204.xml
<?xml version="1.0"?>
<?kli format=BOLDATA sender=DIGSHI receiver=CTII?>
<!DOCTYPE xmledi SYSTEM "204.dtd">

<xmledi doctype="204">

  <transmission id="152783-1042146837">
	  <timestamp>2003-01-09 15:13:57</timestamp>
      <mode>TEST</mode>
      <ack>N</ack>
  </transmission>

  <shipment>
    <header>
	  <type>ORIGINAL</type>
	  <paymentmethod>COLLECT</paymentmethod>
      <bolnumber>152783</bolnumber>
      <ponumber></ponumber>
    </header>
    <location>
      <party type="ORIGIN">
        <name>Northwood Plastics</name>
        <address1>3220 Crocker Ave.</address1>
        <address2></address2>
        <city>SHEBOYGAN</city>
        <state>WI</state>
        <zip>53081</zip>
        <contact>Peter Bins</contact>
        <phone>800-571-0158</phone>
      </party>
      <party type="DESTINATION">
        <name>Tapemark</name>
        <address1>150 Marie Ave. E</address1>
        <address2></address2>
        <city>SAINT PAUL</city>
        <state>MN</state>
        <zip>55118</zip>
        <contact>Jim Maloney</contact>
        <phone>651-450-8773</phone>
      </party>
      <party type="BILLING">
        <name>THE FREIGHT DEPOT</name>
        <address1>191 E. DEERPATH</address1>
        <address2>SUITE 302</address2>
        <city>Lake Forest</city>
        <state>IL</state>
        <zip>60045</zip>
        <contact>CUSTOMER SERVICE</contact>
        <phone>847-283-0092</phone>
      </party>
      <party type="CARRIER">
        <name>Central Transport International</name>
        <scac>CTII</scac>
      </party>
    </location>
    <product>
      <description>1 pallet with two drums of magnetic material</description>
      <weight>475</weight>
      <class>55</class>
      <units>1</units>
      <packaging>PALLET</packaging>
      <hazmat>N</hazmat>
      <hazmatphone></hazmatphone>
    </product>
    <pickup>
      <pickupdate>2003-01-09</pickupdate>
      <pickupafter>08:00:00</pickupafter>
      <pickupbefore>15:00:00</pickupbefore>
    </pickup>
    <services>
      
    </services>
  </shipment>

</xmledi>
