=== youngd24/tfd/interfaces/edi/XML/210.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
     210.dtd

     XMLEDI 210 Document Type Definition

     $Id: 210.dtd,v 1.1 2003/01/03 22:57:46 youngd Exp $

     Contents Copyright (c) 2002, 2003 The Freight Depot

     Darren Young [darren_young@yahoo.com]
-->

<!ELEMENT xmledi (transmission, invoice+)>
<!ATTLIST xmledi doctype CDATA #REQUIRED >

    <!ELEMENT transmission (sender, receiver, date, time)>
    <!ATTLIST transmission transmissionid CDATA #REQUIRED >
        <!ELEMENT sender (#PCDATA)>
        <!ELEMENT receiver (#PCDATA)>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT time (#PCDATA)>

    <!ELEMENT invoice (header, currency, remarks, parties, items)>
        <!ELEMENT header (invoicenumber, pronumber, bolnumber, ponumber, paymentmethod, weightunit, pickupdate, deliverydate, billingdate, totalweight, totalcharges, totalpieces)>
            <!ELEMENT invoicenumber (#PCDATA)>
            <!ELEMENT pronumber (#PCDATA)>
            <!ELEMENT bolnumber (#PCDATA)>
            <!ELEMENT ponumber (#PCDATA)>
            <!ELEMENT paymentmethod (#PCDATA)>
            <!ELEMENT weightunit (#PCDATA)>
            <!ELEMENT pickupdate (#PCDATA)>
            <!ELEMENT deliverydate (#PCDATA)>
            <!ELEMENT billingdate (#PCDATA)>
            <!ELEMENT totalweight (#PCDATA)>
            <!ELEMENT totalcharges (#PCDATA)>
            <!ELEMENT totalpieces (#PCDATA)>

    <!ELEMENT currency (code, exchrate)>
        <!ELEMENT code (#PCDATA)>
        <!ELEMENT exchrate (#PCDATA)>

    <!ELEMENT remarks (message)>
        <!ELEMENT message (#PCDATA)>

    <!ELEMENT parties (party+)>
        <!ELEMENT party (name, address, city, stateprovince, postalcode, countrycode)>
        <!ATTLIST party type CDATA #REQUIRED >
            <!ELEMENT name (#PCDATA)>
            <!ELEMENT address (#PCDATA)>
            <!ELEMENT city (#PCDATA)>
            <!ELEMENT stateprovince (#PCDATA)>
            <!ELEMENT postalcode (#PCDATA)>
            <!ELEMENT countrycode (#PCDATA)>

    <!ELEMENT items (item+)>
        <!ELEMENT item (description, billedquantity, ladingquantity, weight, weightunit, class, charges, specialcharges)>
        <!ATTLIST item id CDATA #REQUIRED >
            <!ELEMENT description (#PCDATA)>
            <!ELEMENT billedquantity (#PCDATA)>
            <!ELEMENT ladingquantity (#PCDATA)>
            <!ELEMENT weight (#PCDATA)>
            <!ELEMENT weightunit (#PCDATA)>
            <!ELEMENT class (#PCDATA)>
            <!ELEMENT charges (#PCDATA)>
            <!ELEMENT specialcharges (#PCDATA)>

=== youngd24/tfd/interfaces/edi/XML/examples/210.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xmledi SYSTEM "210.dtd">

<xmledi doctype="210">
   <transmission transmissionid="0012351">
      <sender>RDWY</sender>
      <receiver>DIGSHI</receiver>
      <date>2003-01-01</date>
      <time>09:49:00</time>
   </transmission>
   <invoice>
      <header>
         <invoicenumber>1651260660</invoicenumber>
         <pronumber>1651260660</pronumber>
         <bolnumber>152961</bolnumber>
         <ponumber>NS</ponumber>
         <paymentmethod>CC</paymentmethod>
         <weightunit>L</weightunit>
         <pickupdate>2003-01-01</pickupdate>
         <deliverydate>2003-01-05</deliverydate>
         <billingdate>2003-01-05</billingdate>
         <totalweight>3200</totalweight>
         <totalcharges>128.61</totalcharges>
         <totalpieces>2</totalpieces>
      </header>
      <currency>
         <code>USD</code>
         <exchrate></exchrate>
      </currency>
      <remarks>
         <message>Balance due in full</message>
      </remarks>
      <parties>      
         <party type="SH (Shipper)">
            <name>Joe Shipper</name>
            <address>666 Elm St.</address>
            <city>Badlands</city>
            <stateprovince>TX</stateprovince>
            <postalcode>12345</postalcode>
            <countrycode>US</countrycode>
         </party>
         <party type="SF (Ship From)">
            <name>Betty Lou Customer</name>
            <address>69 Bang St.</address>
            <city>Oakland</city>
            <stateprovince>CA</stateprovince>
            <postalcode>90277</postalcode>
            <countrycode>US</countrycode>
         </party>
         <party type="CN (Consignee)">
            <name>Bob Consignee</name>
            <address>1212 Lane St.</address>
            <city>Miami</city>
            <stateprovince>FL</stateprovince>
            <postalcode>22345</postalcode>
            <countrycode>US</countrycode>
         </party>
         <party type="BT (Bill To Third Party)">
            <name>The Freight Depot</name>
            <address>191 E. Deerpath Suite 302</address>
            <city>Lake Forest</city>
            <stateprovince>IL</stateprovince>
            <postalcode>60045</postalcode>
            <countrycode>US</countrycode>
         </party>
      </parties>
      <items>
         <item id="1">
            <description>Steel Shelves</description>
            <billedquantity>2</billedquantity>
            <ladingquantity>2</ladingquantity>
            <weight>3200</weight>
            <weightunit>L</weightunit>
            <class>55</class>
            <charges>128.61</charges>
            <specialcharges></specialcharges>
         </item>
      </items>
   </invoice>
</xmledi>

=== youngd24/tfd/interfaces/edi/XML/210.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xmledi SYSTEM "210.dtd">

<xmledi doctype="210">
   <transmission transmissionid="sometext">
      <sender></sender>
      <receiver></receiver>
      <date></date>
      <time></time>
   </transmission>
   <invoice>
      <header>
         <invoicenumber></invoicenumber>
         <pronumber></pronumber>
         <bolnumber></bolnumber>
         <ponumber></ponumber>
         <paymentmethod></paymentmethod>
         <weightunit></weightunit>
         <pickupdate></pickupdate>
         <deliverydate></deliverydate>
         <billingdate></billingdate>
         <totalweight></totalweight>
         <totalcharges></totalcharges>
         <totalpieces></totalpieces>
      </header>
      <currency>
         <code></code>
         <exchrate></exchrate>
      </currency>
      <remarks>
         <message></message>
      </remarks>
      <parties>      
         <party type="SH (Shipper)">
            <name></name>
            <address></address>
            <city></city>
            <stateprovince></stateprovince>
            <postalcode></postalcode>
            <countrycode></countrycode>
         </party>
         <party type="SF (Ship From)">
            <name></name>
            <address></address>
            <city></city>
            <stateprovince></stateprovince>
            <postalcode></postalcode>
            <countrycode></countrycode>
         </party>
         <party type="CN (Consignee)">
            <name></name>
            <address></address>
            <city></city>
            <stateprovince></stateprovince>
            <postalcode></postalcode>
            <countrycode></countrycode>
         </party>
         <party type="BT (Bill To Third Party)">
            <name></name>
            <address></address>
            <city></city>
            <stateprovince></stateprovince>
            <postalcode></postalcode>
            <countrycode></countrycode>
         </party>
      </parties>
      <items>
         <item id="">
            <description></description>
            <billedquantity></billedquantity>
            <ladingquantity></ladingquantity>
            <weight></weight>
            <weightunit>L</weightunit>
            <class></class>
            <charges></charges>
            <specialcharges></specialcharges>
         </item>
      </items>
   </invoice>
</xmledi>
