=== youngd24/tfd/interfaces/edi/XML/old/xmledi.dtd
<?xml version = "1.0"?>

<!-- the xmledi is the root element of the document. it contains a single transmission, and one or more shipments -->
<!ELEMENT xmledi (transmission?, shipment+)>
<!-- the document attribute signifies the edi document type ie (214, 204, 211, 990, 997 etc) -->
<!ATTLIST xmledi document CDATA #IMPLIED>
<!-- the revid attribute lists version of specified document -->
<!ATTLIST xmledi revid CDATA #IMPLIED>
	
	<!-- the transmission element (used only once per xmledi) describes various transmission info -->
	<!ELEMENT transmission (sender, receiver, date, time, (ack, refid)?)>

	<!-- acknowledge attribute for the transmission tag allows for the request of a 990, 997 etc (value should be 'Y' or 'N') -->
	<!ATTLIST transmission acknowledge CDATA #IMPLIED>
	
	<!-- this is the transmission id -->
	<!ATTLIST transmission transmissionid CDATA #IMPLIED>

		<!-- this is the carrier where the transmission originated -->
		<!ELEMENT sender (#PCDATA)>
		<!-- this is the destination company -->
		<!ELEMENT receiver (#PCDATA)>
		<!-- this is the date of the transmission -->
		<!ELEMENT date (#PCDATA)>
		<!-- this is the time of the transmission -->
		<!ELEMENT time (#PCDATA)>
		<!-- this functional acknowledgement allows carriers to send back transmission ok (value should be 0 or 1) -->
		<!ELEMENT ack (#PCDATA)>
		<!-- this is the transmissionid the ack bit references to -->
		<!ELEMENT refid (#PCDATA)>
				
	
	<!-- the shipment element (can occur once or more per transmission) contains any shipment-specific info -->
	<!ELEMENT shipment (header, location?, product?, pickup?, services?, status*, invoice?, pod?)>
		
		<!-- the header element describes any shipment-specific numbers or codes -->
		<!-- header must occure once -->
		<!ELEMENT header (pronumber, bolnumber, ponumber?)>
		
			<!-- the pro number of the carrier -->
			<!ELEMENT pronumber (#PCDATA)>
			<!-- digiship's bill of lading number -->
			<!ELEMENT bolnumber (#PCDATA)>
			<!-- shipper's po -->
			<!ELEMENT ponumber (#PCDATA)>
		
		<!-- the location element contains any addresses associated with the shipment -->
		<!-- location can appear never or once -->
		<!ELEMENT location (party*)>
		
			<!ELEMENT party (name*, address*, city?, state?, zip?, country?)>
			<!-- type describes party. valid values are - (origin, destination, billing, carrier, broker, reroute) -->
			<!ATTLIST party type CDATA #REQUIRED>
			
				<!ELEMENT name (#PCDATA)>
				<!ELEMENT address (#PCDATA)>
				<!ELEMENT city (#PCDATA)>
				<!ELEMENT state (#PCDATA)>
				<!ELEMENT zip (#PCDATA)>
				<!ELEMENT country (#PCDATA)>
		
		<!-- the product element contains any product info for the shipment -->
		<!-- product can appear never or once -->
		<!ELEMENT product (description*, weight, class, units, hazmat?, sku?, packaging?, sic?)>
		
			<!ELEMENT description (#PCDATA)>
			<!ELEMENT weight (#PCDATA)>
			<!ELEMENT class (#PCDATA)>
			<!ELEMENT units (#PCDATA)>
			<!-- note to Jeff, hazmat should be a full element with subs for additional info -->
			<!ELEMENT hazmat (#PCDATA)>	
			<!ELEMENT sku (#PCDATA)>
			<!ELEMENT packaging (#PCDATA)>	
			<!ELEMENT sic (#PCDATA)>
		
		<!-- the pickup element contains any pickup specific info for the shipment 204 -->
		<!-- pickup can appear never or once -->
		<!ELEMENT pickup (pickupdate, pickupafter, pickupbefore)>
		
			<!ELEMENT pickupdate (#PCDATA)>
			<!ELEMENT pickupafter (#PCDATA)>
			<!ELEMENT pickupbefore (#PCDATA)>
		
		<!-- the services element contains any accessorials info for the shipment 204 -->
		<!-- services can appear never or once -->
		<!ELEMENT services (accessorial*)>
		
			<!ELEMENT accessorial (#PCDATA)>

		<!-- the status element contains any shipment statuses for the 214 -->
		<!-- status can appear never or once -->
		<!ELEMENT status (code, reason, city, state, equipment?, equipmentnum?, date, time, timezone, notes*)>
		
			<!-- the code is the status code from the carrier converted to the EDI standard message -->
			<!ELEMENT code (#PCDATA)>
			<!-- the reason is the explanation of the above code -->
			<!ELEMENT reason (#PCDATA)>
			
			<!--already been declared<!ELEMENT city (#PCDATA)>-->
			<!--already been declared<!ELEMENT state (#PCDATA)>-->
			
			<!-- the equipment is the carrier equipment type -->
			<!ELEMENT equipment (#PCDATA)>
			<!-- the equipmentnum is the carrier equipment number -->
			<!ELEMENT equipmentnum (#PCDATA)>
			
			<!-- the date here is the date of the status message -->
			<!--already been declared<!ELEMENT date (#PCDATA)>-->
			<!-- the time here is the time of the status message -->
			<!--already been declared<!ELEMENT time (#PCDATA)>-->
			
			<!-- the timezone is the timezone of the status message -->
			<!ELEMENT timezone (#PCDATA)>
			<!-- the notes allow for any possible notes from the carrier -->
			<!ELEMENT notes (#PCDATA)>
		
		<!-- the invoice element contains the invoice for the shipment -->
		<!-- invoice can appear never or once -->
		<!ELEMENT invoice (invoicenumber, invoicedate, duedate, terms?, item*, totalcharges)>
			
			<!ELEMENT invoicenumber (#PCDATA)>
			<!ELEMENT invoicedate (#PCDATA)>
			<!ELEMENT duedate (#PCDATA)>
			<!ELEMENT terms (#PCDATA)>
			<!ELEMENT item (product?, charge)>
				<!ELEMENT charge (#PCDATA)>
			<!ELEMENT totalcharges (#PCDATA)>

		<!ELEMENT pod EMPTY>

=== youngd24/tfd/interfaces/edi/XML/old/shipment.xml
<?xml version = "1.0"?>
<?kli format=SSMDATA sender=DIGSHI rrr=TEST?>

<!DOCTYPE xmledi SYSTEM "xmledi.dtd">

<xmledi>

	<shipment>
		
		<header>
		
			<pronumber>213123</pronumber>
			<bolnumber>140024</bolnumber>
			<ponumber>ACDA-ADF23</ponumber>
		
		</header>
	
		<location>

			<party type="ORIGIN">
				
				<name>Clement Wheel</name>
				<address>12332 North St</address>
				<address>Dock 4</address>
				<city>Chicago</city>
				<state>IL</state>
				<zip>60607</zip>

			</party>

			<party type="DESTINATION">
				
				<name>BMW Racing</name>
				<address>58 7th Avenue</address>
				<city>New York</city>
				<state>NY</state>
				<zip>01005</zip>

			</party>

			<party type="BILLING">
				
				<name>DigiShip Corporation</name>
				<address>900 N Franklin</address>
				<address>Suite 402</address>
				<city>Chicago</city>
				<state>IL</state>
				<zip>60610</zip>

			</party>

			<party type="CARRIER">
				
				<name>Roadway Express</name>
				
			</party>

		</location>

		<product>
		
			<description>Steel Wheels</description>
			<weight>10000</weight>
			<class>75</class>
			<units>12</units>
			<packaging>skid</packaging>

		</product>

		<pickup>

			<pickupdate>01-01-2000</pickupdate>
			<pickupafter>09:20:00</pickupafter>
			<pickupbefore>14:50:00</pickupbefore>

		</pickup>

		<services>

			<accessorial>Liftgate</accessorial>
			<accessorial>Notify</accessorial>
			<accessorial>Liftgate</accessorial>

		</services>
		

		<status>
			
			<code>Delivered</code>
			<reason>Consignee At Fault</reason>	
			<city>New York</city>
			<state>NY</state>
			<equipment>TL</equipment>
			<equipmentnum>213123</equipmentnum>
			<date>2001-10-14</date>
			<time>13:12:31</time>
			<timezone>EST</timezone>
			<notes>Some notes</notes>
				
		</status>
		

		<status>
			
			<code>Arrived in Pittsburg</code>
			<reason>Breakbulk</reason>	
			<city>Pittsburg</city>
			<state>PA</state>
			<equipment>TL</equipment>
			<equipmentnum>213123</equipmentnum>
			<date>2001-10-13</date>
			<time>13:12:31</time>
			<timezone>EST</timezone>
			<notes>Some notes</notes>
				
		</status>


		<status>
			
			<code>Shipment Picked Up</code>
			<reason>BOL received</reason>	
			<city>Chicago</city>
			<state>IL</state>
			<equipment>TL</equipment>
			<equipmentnum>213123</equipmentnum>
			<date>2001-10-12</date>
			<time>13:12:31</time>
			<timezone>EST</timezone>
			<notes>Some notes</notes>
				
		</status>

		<invoice>

			<invoicenumber>29494292</invoicenumber>
			<invoicedate>10/16/1969</invoicedate>
			<duedate>11/15/1969</duedate>
			<terms>Net 30</terms>
			<item>
				<charge>142.23</charge>
			</item>
			<totalcharges>142.23</totalcharges>
			

		</invoice>

	</shipment>

</xmledi>

=== youngd24/tfd/interfaces/edi/XML/old/xmledi.xml
<?xml version = "1.0"?>

<!DOCTYPE xmledi SYSTEM "xmledi.dtd">

<xmledi document="204" revid="1.4">
	
	<transmission>
	
		<sender>RDWY</sender>
		<receiver>DIGSHI</receiver>
		<date>2001-12-12</date>
		<time>15:45:05</time>

	</transmission>

	<shipment>

		<header>
		
			<pronumber>21412414</pronumber>
			<bolnumber>213902139</bolnumber>
			<ponumber>213-ASD-12</ponumber>
		
		</header>
		
		<location>
		
			<party type="origin">
			
				<name>ABC Company</name>
				<name>Shipping Dept</name>
				<address>1234 ABC Rd.</address>
				<address>Suite 563</address>
				<city>Chicago</city>
				<state>IL</state>
				<zip>60614</zip>
				<country>USA</country>
			
			</party>
			
			<party type="destination">
			
				<name>ABC Company</name>
				<name>Shipping Dept</name>
				<address>1234 ABC Rd.</address>
				<address>Suite 563</address>
				<city>Chicago</city>
				<state>IL</state>
				<zip>60614</zip>
				<country>USA</country>
			
			</party>
			
			<party type="billing">
			
				<name>ABC Company</name>
				<name>Shipping Dept</name>
				<address>1234 ABC Rd.</address>
				<address>Suite 563</address>
				<city>Chicago</city>
				<state>IL</state>
				<zip>60614</zip>
				<country>USA</country>
			
			</party>
		
		</location>
		
		<product>
		
			<description>Steel Wheels</description>
			<weight>10000</weight>
			<class>50</class>
			<units>10</units>
			<hazmat>N</hazmat>
							
		</product>
		
		<pickup>
		
			<pickupdate>2000-11-12</pickupdate>
			<pickupafter>05:00:00</pickupafter>
			<pickupbefore>16:00:00</pickupbefore>
					
		</pickup>
		
		<services>
			
			
		
		</services>
		
		<status>
			
			<code>D1</code>
			<reason>Consignee At Fault</reason>	
			<city>Ithaca</city>
			<state>NY</state>
			<equipment>TL</equipment>
			<equipmentnum>213123</equipmentnum>
			<date>2001-10-12</date>
			<time>13:12:31</time>
			<timezone>EST</timezone>
			<notes></notes>
				
		</status>
		
		<invoice>
		
		</invoice>
	
	</shipment>

</xmledi>

=== youngd24/tfd/interfaces/edi/XML/old/xmledi_2.xml
<?xml version = "1.0"?>

<!DOCTYPE xmledi SYSTEM "xmledi.dtd">


<!-- revid is used to identify the xmledi rev in use here -->
<!-- xmledi doctype="214" revid="0.01" -->

<xmledi doctype="214" revid="0.01">

	<transmission>
		<sender>RDWY</sender>
		<receiver>DIGSHI</receiver>
		<date>2001-12-12</date>
		<time>15:45:05</time>
		<method>INTERNET</method>
	</transmission>

	<shipment pronum="21412414" bolnum="213902139" ponum="213-ASD=12">
		<location>
			<party type="origin">
				<name>ABC Company</name>
				<name>Shipping Dept</name>
				<address>1234 ABC Rd.</address>
				<address>Suite 563</address>
				<city>Chicago</city>
				<state>IL</state>
				<zip>60614</zip>
				<country>USA</country>
			</party>

			<party type="destination">
				<name>ABC Company</name>
				<name>Shipping Dept</name>
				<address>1234 ABC Rd.</address>
				<address>Suite 563</address>
				<city>Chicago</city>
				<state>IL</state>
				<zip>60614</zip>
				<country>USA</country>
			</party>

			<party type="billing">
				<name>ABC Company</name>
				<name>Shipping Dept</name>
				<address>1234 ABC Rd.</address>
				<address>Suite 563</address>
				<city>Chicago</city>
				<state>IL</state>
				<zip>60614</zip>
				<country>USA</country>
			</party>
		</location>

		<product>
			<description>Steel Wheels</description>
			<weight>10000</weight>
			<class>50</class>
			<units>10</units>
			<hazmat>N</hazmat>
		</product>

		<pickup>
			<pickupdate>2000-11-12</pickupdate>
			<pickupafter>05:00:00</pickupafter>
			<pickupbefore>16:00:00</pickupbefore>
		</pickup>

		<services>
			<type id="liftgate">Lift Gate</type>
			<type id="special">Another Special Service</type>
		</services>

	</shipment>

</xmledi>

=== youngd24/tfd/interfaces/edi/XML/old/xmledi214.xml
<?xml version = "1.0"?>

<?kli format=SSMDATA sender=DIGSHI rrr=TEST?>


<!DOCTYPE xmledi SYSTEM "xmledi.dtd">


<xmledi document="214" revid="1.0">

  <transmission>

    <sender>RDWY</sender>

    <receiver>DIGSHI</receiver>

    <date>2001-03-01</date>

    <time>15:45:05</time>

  </transmission>



  <shipment>

    <header>

      <pronumber>21412414</pronumber>

      <bolnumber>10003</bolnumber>

      <ponumber>213-ASD-12</ponumber>

    </header>

		

    <status>

      <code>IN TRANSIT</code>

      <reason>Picked up Dayton</reason>	

      <city>Dayton</city>

      <state>OH</state>

      <equipment>TL</equipment>

      <equipmentnum>213123</equipmentnum>

      <date>2001-03-01</date>

      <time>15:45:05</time>

      <timezone>EST</timezone>

      <notes>Package changed trailers</notes>

    </status>

  </shipment>

</xmledi>

=== youngd24/tfd/interfaces/edi/FTPServer/client/xmldocs/214-shipment_delivered.xml
<?xml version = "1.0"?>

<!DOCTYPE xmledi SYSTEM "xmledi.dtd">

<xmledi document="214" revid="1.0">
  <transmission>
    <sender>RDWY</sender>
    <receiver>DIGSHI</receiver>
    <date>2001-03-01</date>
    <time>15:45:05</time>
  </transmission>

  <shipment>
    <header>
      <pronumber>21412414</pronumber>
      <bolnumber>10003</bolnumber>
      <ponumber>213-ASD-12</ponumber>
    </header>
		
    <status>
      <code>SHIPMENT DELIVERED</code>
      <reason>Delivered to customer</reason>	
      <city>Chicago</city>
      <state>IL</state>
      <equipment>LTL</equipment>
      <equipmentnum>213123</equipmentnum>
      <date>2001-03-01</date>
      <time>15:45:05</time>
      <timezone>EST</timezone>
      <notes>Some notes</notes>
    </status>
  </shipment>
</xmledi>
